app_setori/urls.py
from django.urls import path,include,re_path
# from django.conf.urls import url,handler403

from .views import *
from .views import beranda
from .views import berita
from .views import data_pokok
from .views import faq
from .views import kontak
from .views import layanan
from .views import potensi
from .views import tentang

app_name = 'app_setori'

urlpatterns = [
     path('', beranda.HomeViews.as_view(), name = 'index_home'),
     path('data', data_pokok.Data_pokokViews.as_view(), name = 'data'),
     path('api/kesehatan-data/', data_pokok.KesehatanDataViews.as_view(), name='kesehatan-data'),
     path('detail_data', data_pokok.DetaildataViews.as_view(), name = 'detail_data'),
     
     path('layanan', layanan.LayananViews.as_view(), name = 'layanan'),
     path('faq', faq.FaqViews.as_view(), name = 'faq'),
     path('tentang', tentang.TentangViews.as_view(), name = 'tentang'),
     path('kontak', kontak.KontakViews.as_view(), name = 'kontak'),

     path('berita/',include([
     path('', berita.BeritaViews.as_view(), name = 'berita'),
     path('detail/<slug:slug>/', berita.DetailberitaViews.as_view(), name='detail_berita'),
     ])),

     path('potensi/',include([
          path('kampung', potensi.PotensiViews.as_view(), name = 'kampung'),
          path('distrik', potensi.PotensiDistrikViews.as_view(), name = 'distrik'),
          path('detail/<str:info_wilayah_id>', potensi.DistridetailViews.as_view(), name = 'detail'),
     ])),
     
]

templates/setori/base_layout/base_layout.html
{%  load static %}
<!DOCTYPE html>
<html lang="en">

    <head>

        
		<!-- Basic -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">

		<title>SETORI | Dataset Supiori</title>	

		<meta name="keywords" content="WebSite Template" />
		<meta name="description" content="Porto - Multipurpose Website Template">
		<meta name="author" content="okler.net">

		<!-- Favicon -->
		<link rel="shortcut icon" href="{% static 'img/icons/logo_setori/logo_biasa.png' %}" type="image/x-icon" />
		<link rel="apple-touch-icon" href="{% static 'img/apple-touch-icon.png' %}">

		<!-- Mobile Metas -->
		<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1.0, shrink-to-fit=no">

		<!-- Web Fonts  -->
		<link id="googleFonts" href="https://fonts.googleapis.com/css2?family=Lexend:wght@100..900&family=Playfair+Display:ital,wght@0,400..900;1,400..900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet" type="text/css">

		<!-- Vendor CSS -->
		<link rel="stylesheet" href="{% static 'setori/vendor/bootstrap/css/bootstrap.min.css' %}">
		<link rel="stylesheet" href="{% static 'setori/vendor/fontawesome-free/css/all.min.css' %}">
		<link rel="stylesheet" href="{% static 'setori/vendor/animate/animate.compat.css' %}">
		<link rel="stylesheet" href="{% static 'setori/vendor/simple-line-icons/css/simple-line-icons.min.css' %}">
		<link rel="stylesheet" href="{% static 'setori/vendor/owl.carousel/assets/owl.carousel.min.css' %}">
		<link rel="stylesheet" href="{% static 'setori/vendor/owl.carousel/assets/owl.theme.default.min.css' %}">
		<link rel="stylesheet" href="{% static 'setori/vendor/magnific-popup/magnific-popup.min.css' %}">

		<!-- Theme CSS -->
		<link rel="stylesheet" href="{% static 'setori/css/theme.css' %}">
		<link rel="stylesheet" href="{% static 'setori/css/theme-elements.css' %}">
		<link rel="stylesheet" href="{% static 'setori/css/theme-blog.css' %}">
		<link rel="stylesheet" href="{% static 'setori/css/theme-shop.css' %}">

		<!-- Demo CSS -->
		<link rel="stylesheet" href="{% static 'setori/css/demos/demo-accounting-1.css' %}">

		<!-- Skin CSS -->
		<link id="skinCSS" rel="stylesheet" href="{% static 'setori/css/skins/skin-accounting-1.css' %}">
        
		<!-- Theme Custom CSS -->
		<link rel="stylesheet" href="{% static 'setori/css/custom.css' %}">
		<script src="https://code.highcharts.com/highcharts.js"></script>
		<script src="https://code.highcharts.com/modules/exporting.js"></script>
		<script src="https://code.highcharts.com/modules/export-data.js"></script>
		<script src="https://code.highcharts.com/modules/accessibility.js"></script>

		<!-- ckeditor -->
		<link rel="stylesheet" href="https://cdn.ckeditor.com/ckeditor5/43.2.0/ckeditor5.css" />


			{% block css %} {% endblock css %} 
		
	</head>

<body>

    {% include 'setori/base_layout/navbar.html' %}
	
  

    {% block main %} {% endblock main %} 
    {% include 'setori/base_layout/footer.html' %}
    
    {% include 'setori/base_layout/chart.html' %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    {% block js %} {% endblock js %} 

    <!-- Vendor -->
	<script src="{% static 'setori/vendor/plugins/js/plugins.min.js' %}"></script>

		<!-- Theme Base, Components and Settings -->
	<script src="{% static 'setori/js/theme.js' %}"></script>

		<!-- Demo -->
	<script src="{% static 'setori/js/demos/demo-accounting-1.js' %}"></script>

		<!-- Theme Custom -->
	<script src="{% static 'setori/js/custom.js' %}"></script>

		<!-- Theme Initialization Files -->
	<script src="{% static 'setori/js/theme.init.js' %}"></script>

	<!-- Current Page Vendor and Views -->
	<script src="{% static 'setori/js/views/view.contact.js' %}"></script>

	<script type="importmap">
		{
			"imports": {
				"ckeditor5": "https://cdn.ckeditor.com/ckeditor5/43.2.0/ckeditor5.js",
				"ckeditor5/": "https://cdn.ckeditor.com/ckeditor5/43.2.0/"
			}
		}
	</script>

	
</body>
</html>

templates/setori/base_layout/footer.html
{% load static %}
{% block css %}
{% endblock css %}

<footer id="footer" class="border-0 bg-light px-3 px-lg-5 pt-0 text-3">
    <div class="container pb-lg-4 pt-5">
        <div class="row pt-3">
            <!--ke 1-->
            <div class="col-lg-4">
                <a href="index.html">
                    <img alt="Porto" width="90%" height="auto" src="{% static 'img/icons/logo_setori/logo_setori_hitam.png' %}">
                </a>
            </div>

            <!--ke 2-->
            <div class="col-sm-6 col-lg-4 pt-4 pt-lg-0">
                <h4 class="text-color-dark font-weight-bold mb-3">Setori</h4>

                <p class="text-3-5 text-color-grey">Setori - Menuju Kesehatan Masyarakat yang Lebih Baik. Setori menyediakan infografik data kesehatan Kabupaten Supiori lengkap hingga rinciannya di kampung, serta berita terbaru yang terkait dengan Supiori untuk informasi terkini dan pemahaman data yang mudah.</p>

                <ul class="social-icons social-icons-clean social-icons-medium">
                    <li class="social-icons-instagram">
                        <a href="http://www.instagram.com/" target="_blank" title="Instagram">
                            <i class="fab fa-instagram"></i>
                        </a>
                    </li>
                    <li class="social-icons-x">
                        <a href="http://www.x.com/" target="_blank" title="X">
                            <i class="fab fa-x-twitter"></i>
                        </a>
                    </li>
                    <li class="social-icons-facebook">
                        <a href="http://www.facebook.com/" target="_blank" title="Facebook">
                            <i class="fab fa-facebook-f"></i>
                        </a>
                    </li>
                </ul>
            </div>

            <!--ke 3-->
            <div class="col-lg-3 pt-4 pt-lg-0";>
                <h4 class="text-color-dark font-weight-bold mb-3"  style="margin: 0 auto; text-align: center">Maps</h4>
                <p class="text-3-5 text-color-grey">Hubungi kami di: Marsram, Kec. Supiori Tim., Kabupaten Supiori, Papua 98161</p>
            </div>
        </div>
    </div>

    <!--bawahan-->
    <div class="footer-copyright bg-transparent pb-5">
        <div class="container">
            <hr>
            <div class="row">
                <div class="col-lg-6 text-center text-lg-start py-3">
                    <p class="text-3 mb-0 opacity-6">© 2024 Setori is Proudly Powered by <a href="http://www.okler.net/" target="_blank" class="text-decoration-underline text-color-secondary text-color-hover-primary">Okler</a></p>
                </div>
                <div class="col-lg-6 py-3 text-center text-lg-end">
                    <a href="{% url 'app_setori:kontak' %}" class="text-color-grey text-color-hover-primary">Privacy Policy</a>
                    <a href="{% url 'app_setori:kontak' %}" class="text-color-grey text-color-hover-primary ms-3">Terms of Use</a>
                </div>
            </div>
        </div>
    </div>
</footer>

templates/setori/base_layout/navbar.html
{%  load static %}
{% block css %}
<style>
#header {
    position: sticky; /* Membuat navbar tetap di atas */
    top: 0; /* Mengatur posisi dari atas */
    left: 0; /* Mengatur posisi dari kiri */
    right: 0; /* Mengatur posisi dari kanan */
    z-index: 1000; /* Menjaga agar navbar di atas elemen lainnya */
    transition: background-color 0.3s; /* Menambahkan efek transisi saat mengubah warna latar belakang */
}

.header-body {
    background: #367588; /* Warna latar belakang navbar */
}
</style>

{% endblock css %}
<header id="header">
    <div class="header-body border-top-0 h-auto box-shadow-none" style="background:#367588;">
        <div class="container-fluid px-3 px-lg-5 p-static">
            <div class="row align-items-center py-3">
                <div class="col-auto col-lg-2 col-xxl-3 me-auto me-lg-0">
                    <div class="header-logo" data-clone-element-to="#offCanvasLogo">
                        <a href="{% url 'app_setori:index_home' %}">
                            <img alt="Logo_Setori" width="200" height="auto" src="{% static 'img/icons/logo_setori/S (500 x 170 piksel) (1).png' %}">
                        </a>
                    </div>
                </div>
                <div class="col-auto col-lg-9 col-xxl-6 justify-content-lg-center">
                    <div class="header-nav header-nav-links justify-content-lg-center">
                        <div class="header-nav-main header-nav-main-text-capitalize header-nav-main-arrows header-nav-main-effect-2">
                            <nav class="collapse">
                                <ul class="nav nav-pills" id="mainNav">
                                    <li><a href="{% url 'app_setori:index_home' %}" class="nav-link" style="color:white;">Beranda</a></li>
                                    <li><a class="nav-link" href="{% url 'app_setori:data' %}" style="color:white;">Data Pokok</a></li>
                                    <li><a class="nav-link" href="{% url 'app_setori:berita' %}" style="color:white;">Berita</a></li>
                                    <li class="dropdown">
                                        <a class="nav-link dropdown-toggle" style="color:white;">Potensi Daerah</a>
                                        <ul class="dropdown-menu">
                                            <li><a href="{% url 'app_setori:distrik' %}" class="dropdown-item anim-hover-translate-right-5px transition-3ms bg-transparent text-color-hover-primary text-lg-2 py-lg-2">Potensi Daerah Distrik</a></li>
                                            <li><a href="{% url 'app_setori:kampung' %}" class="dropdown-item anim-hover-translate-right-5px transition-3ms bg-transparent text-color-hover-primary text-lg-2 py-lg-2">Potensi Daerah Kampung</a></li>
                                        </ul>
                                    </li>
                                    <li><a class="nav-link" href="{% url 'app_setori:tentang' %}" style="color:white;">Tentang Kami</a></li>
                                    <li><a class="nav-link" href="{% url 'app_setori:layanan' %}" style="color:white;">Layanan</a></li>
                                    <li><a class="nav-link" href="{% url 'app_setori:faq' %}" style="color:white;">FAQ</a></li>
                                    <li><a class="nav-link" href="{% url 'app_setori:kontak' %}" style="color:white;">Kontak</a></li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                </div>
                <div class="col-auto col-lg-2 col-xxl-3">
                    <div class="d-flex justify-content-end align-items-center">
                        <button class="btn header-btn-collapse-nav rounded-pill" style="background:transparent" data-bs-toggle="offcanvas" href="#offcanvasMain" role="button" aria-controls="offcanvasMain">
                            <i class="fas fa-bars" style="font-size: 24px;"></i>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

<div class="offcanvas offcanvas-start" data-bs-scroll="true" tabindex="-1" id="offcanvasMain" aria-labelledby="offcanvasMain" style="background:#367588;">
    <div class="offcanvas-header">
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">
        <div class="mb-4" id="offCanvasLogo"></div>
        <nav class="offcanvas-nav w-100" id="offCanvasNav"></nav>
    </div>
</div>

<script>
// Skrip JavaScript untuk mengubah warna background saat scroll
document.addEventListener("scroll", function () {
    const header = document.getElementById("header");
    const scrollPosition = window.scrollY || document.documentElement.scrollTop;

    if (scrollPosition > 50) {
        header.style.backgroundColor = "rgba(54, 117, 136, 0.9)";
    } else {
        header.style.backgroundColor = "#367588";
    }
});
</script>