app_setori/urls.py
from django.urls import path,include,re_path
# from django.conf.urls import url,handler403

from .views import *
from .views import beranda
from .views import berita
from .views import data_pokok
from .views import faq
from .views import kontak
from .views import layanan
from .views import potensi
from .views import tentang

app_name = 'app_setori'

urlpatterns = [
     path('', beranda.HomeViews.as_view(), name = 'index_home'),
     path('data', data_pokok.Data_pokokViews.as_view(), name = 'data'),
     path('api/kesehatan-data/', data_pokok.KesehatanDataViews.as_view(), name='kesehatan-data'),
     path('detail_data', data_pokok.DetaildataViews.as_view(), name = 'detail_data'),
     
     path('layanan', layanan.LayananViews.as_view(), name = 'layanan'),
     path('faq', faq.FaqViews.as_view(), name = 'faq'),
     path('tentang', tentang.TentangViews.as_view(), name = 'tentang'),
     path('kontak', kontak.KontakViews.as_view(), name = 'kontak'),

     path('berita/',include([
     path('', berita.BeritaViews.as_view(), name = 'berita'),
     path('detail/<slug:slug>/', berita.DetailberitaViews.as_view(), name='detail_berita'),
     ])),

     path('potensi/',include([
          path('kampung', potensi.PotensiViews.as_view(), name = 'kampung'),
          path('distrik', potensi.PotensiDistrikViews.as_view(), name = 'distrik'),
          path('detail/<str:info_wilayah_id>', potensi.DistridetailViews.as_view(), name = 'detail'),
     ])),
     
]

app_setori/views/berita.py
from django.shortcuts import render, redirect
from django.db import transaction 
from django.views import View
from admin_setori.models import *
from django.contrib import messages
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django import forms
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from admin_setori.decorators import role_required
from django.utils.decorators import method_decorator
from django.core.paginator import Paginator

class BeritaViews(View):
    def get(self, request):
        dt_berita = News.objects.filter(deleted_at__isnull=True).order_by('-created_at')  # Ambil semua berita yang tidak dihapus
        dt_kategori = Category.objects.filter(deleted_at__isnull=True)  # Ambil semua kategori yang tidak dihapus

        paginator = Paginator(dt_berita, 6)  # Batasi 10 berita per halaman

        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        data = {
            'dt_berita': dt_berita,  # Ganti dengan data yang sudah dipaginate
            'dt_kategori': dt_kategori, 
            'page_obj': page_obj
        }
        return render(request, 'setori/berita/index.html', data)

class DetailberitaViews(View):
    def get(self, request, slug):
        detail_berita = get_object_or_404(News,slug=slug)
        dt_berita = News.objects.filter(deleted_at__isnull=True).order_by('-created_at')  # Ambil semua berita yang tidak dihapus
        dt_category = Category.objects.filter(deleted_at__isnull = True)  # Ambil semua kategori yang tidak dihapus

        paginator = Paginator(dt_berita, 6)  # Batasi jumlah berita yang ditampilkan per halaman (6 berita)
        page_number = request.GET.get('page')  # Ambil nomor halaman dari query parameter
        page_obj = paginator.get_page(page_number)  # Ambil berita untuk halaman yang diminta

        data = {
            'dt_berita': dt_berita,
            'detail_berita': detail_berita,
            'dt_category': dt_category,
            'page_obj': page_obj
        }
        return render(request, 'setori/berita/detail_berita.html', data)
     

templates/setori/berita/detail_berita.html
{% extends 'setori/base_layout/base_layout.html' %} 
{% load static %}

{% block css %}
<style>
    .read__title {
        font-family: 'Lexend', sans-serif;
        font-weight: 500;
    }
    .isi-berita {
    font-size: 250%;
    }
    .recent-post {
        border: 1px solid #ddd; /* Garis batas kotak */
        border-radius: 8px; /* Sudut melengkung */
        overflow: hidden; /* Menghindari gambar yang meluap */
        box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1); /* Efek bayangan */
        transition: transform 0.3s; /* Efek transisi saat hover */
    }

    .recent-post:hover {
        transform: translateY(-5px); /* Efek saat hover */
    }

    img {
        object-fit: cover; /* Mengatur gambar agar sesuai kotak */
    }
    .grow img{
        transition: 1s ease;
    }

    .grow img:hover{
        -webkit-transform: scale(1.2);
        -ms-transform: scale(1.2);
        transform: scale(1.2);
        transition: 1s ease;
    }
    .judul_berita {
    color: #000; /* Warna default, sesuaikan dengan kebutuhan Anda */
    transition: color 0.2s ease; /* Efek transisi */
    }

    .judul_berita:hover {
    color: #164b85; /* Warna saat di-hover, sesuaikan dengan kebutuhan Anda */
    }
</style>
{% endblock css %}


{% block main %} 
<div class="body">
    
        <div class="body">
            <div class="page-header" style="position: relative; margin-bottom: 0; overflow: hidden;">
                <img src="{% static 'img/header/atasan.jpg' %}" alt="Header Background" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; object-fit: cover; z-index: 0;">
                <div class="container p-relative z-index-1 py-2">
                    <div class="row mh-200px mh-lg-300px align-items-center py-4">
                        <div class="col">
                            <div class="appear-animation" data-appear-animation="fadeIn" data-appear-animation-delay="200">
                                <h1 class="text-9 text-lg-12 text-color-light font-weight-semibold line-height-1 mb-2" >Detail Berita</h1>
                            </div>
                            <div class="appear-animation" data-appear-animation="fadeIn" data-appear-animation-delay="200">
                                <ul class="breadcrumb d-flex text-3-5 font-weight-semi-bold pb-2 mb-3">
                                    <li><a href="{% url 'app_setori:index_home' %}" class="text-light text-decoration-none">Beranda</a></li>
                                    <li class="active text-color-light opacity-7">Detail Berita</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>


    <div role="main" class="main px-3 px-lg-5"> 
        <div class="container mt-lg-5 pt-5">

            <div class="row">
                <div class="col-lg-8 mb-5 mb-lg-0">

                    <article>
                        <div class="card border-0">
                            <div class="card-body p-0">
                                <h1 class="read__title">{{ detail_berita.title }}</h1>
                                
                                <p class="text-uppercase text-3 font-weight-semibold mb-3 text-color-secondary d-flex justify-content-between">
                                    <span>Penulis: {{ detail_berita.created_by.username }}</span>
                                    <span>Tanggal Terbit: {{ detail_berita.created_at }}</span>
                                </p>
                                
         
                                <div class="post-image pb-4">
                                    <img class="card-img-top border-radius-2" src="{{ detail_berita.thumbnail.url }}" alt="Card Image">
                                </div>

                                <div class="card-body p-0">
                                    <!-- Go to www.addtoany.com to customize -->
                                    <!-- AddToAny BEGIN -->
                                    <div class="a2a_kit a2a_kit_size_32 a2a_default_style">
                                        <a class="a2a_dd" href="https://www.addtoany.com/share"></a>
                                        <a class="a2a_button_facebook"></a>
                                        <a class="a2a_button_x"></a>
                                        <a class="a2a_button_copy_link"></a>
                                    </div>
                                    <script async src="https://static.addtoany.com/menu/page.js"></script>
                                    <!-- AddToAny END -->
                                    <div class="isi berita">
                                        <p>{{ detail_berita.content|safe }}</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </article>

                </div>

                <!--samping-->
                <div class="blog-sidebar col-lg-4 pt-4 pt-lg-0">
                    <aside class="sidebar">
                        <div class="px-3 mt-4">
                            <h3 class="text-color-dark text-capitalize font-weight-bold text-5 m-0 mb-3" style="text-align: center;">Kategori Berita Lainnya</h3>
                            <div class="pb-2 mb-1">
                                {% for kategori in dt_category %}
                                <div class="">
                                    <h5 class="my-2">
                                        - {{ kategori.name }}
                                    </h5>
                                </div>                                
                                {% endfor %}
                            </div>
                
                            <h3 class="text-color-dark text-capitalize font-weight-bold text-5 m-0 mb-3" style="text-align: center;">Berita lainnya</h3>
                            <div class="pb-2 mb-1">
                                {% for berita in page_obj %}
                                <div class="recent-post" style="margin-bottom: 20px; border: 1px solid #ddd; border-radius: 8px; overflow: hidden; box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);">
                                    <img src="{{ berita.thumbnail.url }}" style="width: 100%; height: 150px; margin-bottom: 10px;">
                                    <h5 class="my-2">
                                        <a href="{% url 'app_setori:detail_berita' berita.slug %}" class="judul_berita text-3 d-block pb-3 line-height-4" style="padding: 10px 15px; display: block;">
                                            {{ berita.title }}
                                        </a>
                                    </h5>
                                </div>                                
                                {% endfor %}
                            </div>
                        </div>
                    </aside>
                </div>
                
            </div>

        </div>

    </div>
</div>

{% endblock main %} 

templates/setori/berita/index.html
{% extends 'setori/base_layout/base_layout.html' %} 
{% load static %}

{% block css %}
<style>
/* Dropdown */
/* Dropdown Button Styles */
.dropbtn {
    background-color: #367588;
    color: white;
    padding: 12px 20px;
    font-size: 16px;
    border: none;
    border-radius: 5px;
    cursor: pointer;
    position: relative;
    transition: background-color 0.3s;
    display: flex;
    align-items: center;
}

.dropbtn i {
    margin-left: 5px; /* Spasi antara teks dan ikon */
}

/* Change background color on hover */
.dropbtn:hover {
    background-color: #367588;
}

/* Dropdown Container Styles */
.dropdown {
    position: relative;
    display: inline-block;
}

/* Dropdown Content Styles */
.dropdown-content {
    display: none;
    position: absolute;
    background-color: #ffffff;
    min-width: 160px;
    box-shadow: 0px 8px 16px rgba(0, 0, 0, 0.2);
    z-index: 1;
    border-radius: 5px;
    opacity: 0; /* Awalnya tidak terlihat */
    transition: opacity 0.3s ease;
    transform: translateY(10px); /* Efek sliding */
}

/* Dropdown links */
.dropdown-content a {
    color: #333;
    padding: 12px 16px;
    text-decoration: none;
    display: block;
    transition: background-color 0.3s;
}

/* Change background color on hover */
.dropdown-content a:hover {
    background-color: #f1f1f1;
}

/* Show Dropdown Content on Hover */
.dropdown:hover .dropdown-content {
    display: block;
    opacity: 1; /* Menampilkan dropdown */
    transform: translateY(0); /* Menghilangkan efek sliding */
}

/* Search bar */
/* Search Container Styles */
.search-container {
    display: flex;
    align-items: center;
}

/* Search Input Styles */
.search-input {
    padding: 10px 15px;
    border: 2px solid #367588;
    border-radius: 5px 0 0 5px;
    outline: none;
    font-size: 16px;
    width: 200px; /* Lebar input bisa disesuaikan */
    transition: border-color 0.3s;
}

/* Search Input Hover Effect */
.search-input:focus {
    border-color: #0056b3;
}

/* Search Button Styles */
.search-button {
    padding: 10px 15px;
    background-color: #367588;
    color: white;
    border: none;
    border-radius: 0 5px 5px 0;
    cursor: pointer;
    transition: background-color 0.3s;
    display: flex;
    align-items: center;
}

/* Change background color on hover */
.search-button:hover {
    background-color: #0056b3;
}

/* Font Awesome Icon Size */
.search-button i {
    font-size: 16px; /* Ukuran ikon */
}

.judul_berita {
  color: #000; /* Warna default, sesuaikan dengan kebutuhan Anda */
  transition: color 0.2s ease; /* Efek transisi */
}

.judul_berita:hover {
  color: #164b85; /* Warna saat di-hover, sesuaikan dengan kebutuhan Anda */
}



</style>
{% endblock css %}

{% block main %} 
        <!-- header -->
        <div class="body">
            <div class="page-header" style="position: relative; margin-bottom: 0; overflow: hidden;">
                <img src="{% static 'img/header/atasan.jpg' %}" alt="Header Background" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; object-fit: cover; z-index: 0;">
                <div class="container p-relative z-index-1 py-2">
                    <div class="row mh-200px mh-lg-300px align-items-center py-4">
                        <div class="col">
                            <div class="appear-animation" data-appear-animation="fadeIn" data-appear-animation-delay="200">
                                <h1 class="text-9 text-lg-12 text-color-light font-weight-semibold line-height-1 mb-2">Berita</h1>
                            </div>
                            <div class="appear-animation" data-appear-animation="fadeIn" data-appear-animation-delay="200">
                                <ul class="breadcrumb d-flex text-3-5 font-weight-semi-bold pb-2 mb-3">
                                    <li><a href="{% url 'app_setori:index_home' %}" class="text-light text-decoration-none">Beranda</a></li>
                                    <li class="active text-color-light opacity-7">Berita</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>


        <div class="bg-grey-100 px-3 px-xl-0 border-radius-2-bottom p-relative overflow-hidden">
            <!-- News -->
            <div class="container">
                <div class="row pt-5">
                    {% for berita in page_obj %}
                    <div class="col-lg-4 mb-4 pb-1 appear-animation" data-appear-animation="fadeInUpShorter" data-appear-animation-delay="400">
                        <article class="post">
                            <div class="card rounded-3 border-0 bg-transparent box-shadow-10 box-shadow-1 box-shadow-1-hover anim-hover-translate-top-10px transition-3ms">
                                <div class="p-relative rounded-3 overflow-hidden">
                                    <a href="{% url 'app_setori:detail_berita' berita.slug %}" class="text-decoration-none">
                                        <img class="card-img-top" src="{{ berita.thumbnail.url }}" loading="lazy" alt="Card Image" width="100%" height="200px" object-fit="cover">
                                    </a>
                                    <div class="card-body bg-light p-4">
                                        <span class="badge badge-dark badge-sm rounded-pill text-uppercase me-1">{{ berita.category.name }}</span>
                                        <h4 class="my-2">
                                            <a href="{% url 'app_setori:detail_berita' berita.slug %}" class="judul_berita">
                                              {{ berita.title }}
                                            </a>
                                        </h4>                                          
                                        <p class="card-text text-3-5 mb-1"><p>{{ berita.content|safe|slice:":100" }}...</p>
                                        <a href="{% url 'app_setori:detail_berita' berita.slug %}" class="read-more text-color-secondary font-weight-semibold text-2">Read More <i class="fas fa-angle-right position-relative top-1 ms-1"></i></a>
                                        <div class="d-flex align-items-center mt-3 pt-1">
                                            <img src="img/avatars/avatar.jpg" loading="lazy" class="img-fluid rounded-circle me-2" width="25" alt="">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </article>
                    </div>
                    {% endfor %}
                    
                </div>
                <!-- Kontrol Pagination -->
                <div class="pt-3 pb-5">
                    <ul class="pagination pagination-rounded pagination-md justify-content-center">
                        <!-- Previous Page Link -->
                        {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link bg-transparent text-dark" href="?page={{ page_obj.previous_page_number }}" data-cursor-effect-hover="fit"><i class="fas fa-angle-left"></i></a>
                        </li>
                        {% else %}
                        <li class="page-item disabled">
                            <span class="page-link bg-transparent text-dark"><i class="fas fa-angle-left"></i></span>
                        </li>
                        {% endif %}

                        <!-- Page Number Links -->
                        {% for num in page_obj.paginator.page_range %}
                        {% if page_obj.number == num %}
                        <li class="page-item active"><a class="page-link bg-secondary text-light border-color-secondary" href="?page={{ num }}" data-cursor-effect-hover="fit">{{ num }}</a></li>
                        {% elif num > page_obj.number|add:-3 and num < page_obj.number|add:3 %}
                        <li class="page-item"><a class="page-link bg-transparent text-dark" href="?page={{ num }}" data-cursor-effect-hover="fit">{{ num }}</a></li>
                        {% endif %}
                        {% endfor %}

                        <!-- Next Page Link -->
                        {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link bg-transparent text-dark" href="?page={{ page_obj.next_page_number }}" data-cursor-effect-hover="fit"><i class="fas fa-angle-right"></i></a>
                        </li>
                        {% else %}
                        <li class="page-item disabled">
                            <span class="page-link bg-transparent text-dark"><i class="fas fa-angle-right"></i></span>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="offcanvas offcanvas-start" data-bs-scroll="true" tabindex="-1" id="offcanvasMain" aria-labelledby="offcanvasMain">
    <div class="offcanvas-header">
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">
        <div class="mb-4" id="offCanvasLogo"></div>
        <nav class="offcanvas-nav w-100" id="offCanvasNav"></nav>
    </div>
</div>

{% endblock main %} 