app_setori/urls.py
from django.urls import path,include,re_path
# from django.conf.urls import url,handler403

from .views import *
from .views import beranda
from .views import berita
from .views import data_pokok
from .views import faq
from .views import kontak
from .views import layanan
from .views import potensi
from .views import tentang

app_name = 'app_setori'

urlpatterns = [
     path('', beranda.HomeViews.as_view(), name = 'index_home'),
     path('data', data_pokok.Data_pokokViews.as_view(), name = 'data'),
     path('api/kesehatan-data/', data_pokok.KesehatanDataViews.as_view(), name='kesehatan-data'),
     path('detail_data', data_pokok.DetaildataViews.as_view(), name = 'detail_data'),
     
     path('layanan', layanan.LayananViews.as_view(), name = 'layanan'),
     path('faq', faq.FaqViews.as_view(), name = 'faq'),
     path('tentang', tentang.TentangViews.as_view(), name = 'tentang'),
     path('kontak', kontak.KontakViews.as_view(), name = 'kontak'),

     path('berita/',include([
     path('', berita.BeritaViews.as_view(), name = 'berita'),
     path('detail/<slug:slug>/', berita.DetailberitaViews.as_view(), name='detail_berita'),
     ])),

     path('potensi/',include([
          path('kampung', potensi.PotensiViews.as_view(), name = 'kampung'),
          path('distrik', potensi.PotensiDistrikViews.as_view(), name = 'distrik'),
          path('detail/<str:info_wilayah_id>', potensi.DistridetailViews.as_view(), name = 'detail'),
     ])),
     
]

templates/setori/potensidaerah/detaildistrik.html
{% extends 'setori/base_layout/base_layout.html' %} 
{% load static %}
{% block css %}
<style>
    .header {
        background-color: #6c757d;
        padding: 10px;
        color: white;
    }
    .section-title {
        text-align: center;
        margin: 20px 0;
    }
    .content {
        padding: 20px;
    }
    .data-section, .info-section {
        border: 1px solid #dee2e6;
        margin-bottom: 20px;
        padding: 15px;
    }
    .table-custom th, .table-custom td {
        padding: 10px;
    }
    .section-title {
            text-align: center;
            margin: 20px 0;
            font-weight: bold;
            font-size: 1.5rem;
            border-bottom: 2px solid #dee2e6;
            display: inline-block;
            padding-bottom: 5px;
        }
        .card-header-custom {
            background-color: #367588;
            color: white;
            font-weight: bold;
        }
        .info-section p {
            background-color: #f8f9fa;
            padding: 10px;
            border-radius: 5px;
            margin-bottom: 5px;
        }
        .data-section {
            margin: 20px 0;
        }
        .data-section h3 {
            text-align: center;
            margin-bottom: 20px;
            font-weight: bold;
            font-size: 1.5rem;
        }
        .data-section p {
            background-color: #f8f9fa;
            padding: 10px;
            border-radius: 5px;
            margin-bottom: 5px;
        }
        .info-title {
            text-align: center;
            font-weight: bold;
            margin: 20px 0;
        }
        .map-container img {
            width: 100%;
            border-radius: 5px;
            margin-top: 20px;
        }
        .content-container {
            text-align: center;
        }
    </style>
</style> 
{% endblock css %} 

{% block main %}  
<div class="container-fluid">
    <!-- Section Title -->
    <div class="body">
        <div class="page-header" style="position: relative; margin-bottom: 0; overflow: hidden;">
            <img src="{% static 'img/header/atasan.jpg' %}" alt="Header Background" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; object-fit: cover; z-index: 0;">
            <div class="container p-relative z-index-1 py-2">
                <div class="row mh-200px mh-lg-300px align-items-center py-4">
                    <div class="col">
                        <div class="appear-animation" data-appear-animation="fadeIn" data-appear-animation-delay="200">
                            <h1 class="text-9 text-lg-12 text-color-light font-weight-semibold line-height-1 mb-2">Detail Potensi</h1>
                        </div>
                        <div class="appear-animation" data-appear-animation="fadeIn" data-appear-animation-delay="200">
                            <ul class="breadcrumb d-flex text-3-5 font-weight-semi-bold pb-2 mb-3">
                                <li><a href="{% url 'app_setori:index_home' %}" class="text-light text-decoration-none">Potensi</a></li>
                                <li class="active text-color-light opacity-7">Detail Potensi</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Data Section -->
    <div class="row content">
        <div class="col-md-6 data-section">
            <div class="container">
                <div class="row data-section">
                    <div class="col-12">
                        <div class="card">
                            <img src="{% static 'img/potensi/detail_1.jpg' %}" class="card-img-top" alt="Image of Supiori Selatan">
                            <div class="card-body">
                                <h3>Informasi</h3>
                                <div class="content-container">
                                    <p><strong>Distrik:</strong> Supiori Selatan</p>
                                    <p><strong>Luas Wilayah:</strong> 1000 km</p>
                                    <p><strong>Jumlah Penduduk:</strong> 1000 Jiwa</p>
                                    <p><strong>Kepadatan Penduduk:</strong> 1000 jiwa/km</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row data-section">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <h3>Maps</h3>
                                <div class="map-container" style="height: 400px;">
                                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3989.47268893396!2d135.72742674436404!3d-0.7541726980906849!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x680171f324b75afb%3A0xc3480285d5705e8e!2sDinas%20Kesehatan!5e0!3m2!1sid!2sid!4v1728291617820!5m2!1sid!2sid" width="100%" height="100%" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-6 data-section">       
            <!-- Section Title -->
            <div class="row">
                <div class="col text-center">
                    <h3 class="section-title">Data Umum</h3>
                </div>
            </div>
            <!-- Info Section -->
            <div class="row">
                <div class="col-md-6">
                    <div class="card mb-4">
                        <div class="card-header card-header-custom">
                            Info Wilayah
                        </div>
                        <div class="card-body">
                            <p><strong>Kode Kecamatan:</strong> -</p>
                            <p><strong>Total Jiwa:</strong> -</p>
                            <p><strong>Laki-laki:</strong> -</p>
                            <p><strong>Perempuan:</strong> -</p>
                            <p><strong>Total OAP:</strong> -</p>
                            <p><strong>Total Non OAP:</strong> -</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="card mb-4">
                        <div class="card-header card-header-custom">
                            Batas Wilayah
                        </div>
                        <div class="card-body">
                            <p><strong>Utara:</strong> -</p>
                            <p><strong>Selatan:</strong> -</p>
                            <p><strong>Timur:</strong> -</p>
                            <p><strong>Barat:</strong> -</p>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Facilities Section -->
            <div class="row">
                <div class="col">
                    <div class="card mb-4">
                        <div class="card-header card-header-custom">
                            Sarana dan Prasarana
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-3">
                                    <p><strong>Puskesmas:</strong> -</p>
                                    <p><strong>Posyandu:</strong> -</p>
                                    <p><strong>Pondok Bersalin:</strong> -</p>
                                    <p><strong>Rumah Sakit:</strong> -</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
    </div>

    <!-- Table Section -->
    <div class="row content">
        <div class="col">
            <table class="table table-bordered table-custom">
                <thead>
                    <tr>
                        <th>Nama Distrik</th>
                        <th>Ibu Kota</th>
                        <th>Jumlah Kampung</th>
                        <th>Daftar Kampung</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Supiori Selatan</td>
                        <td>Masyarakat</td>
                        <td>7</td>
                        <td>Awaik, Brak, Bidayam, Famfui, Masyarakat, Odet, Waidori</td>
                    </tr>
                    <tr>
                        <td>Supiori Utara</td>
                        <td>Fanjar</td>
                        <td>5</td>
                        <td>Fanjar, Korido, Jopesi, Warebo, Wirabet</td>
                    </tr>
                    <tr>
                        <td>Supiori Timur</td>
                        <td>Sorendiweri</td>
                        <td>10</td>
                        <td>Doudule, Jekor, Mamdas, Sawata, Sorendiweri, Ansudu, Inswambesi, Kumpuneyendi, Manjasiwona, Ansus Besar</td>
                    </tr>
                    <tr>
                        <td>Kepulauan Aruri</td>
                        <td>Menwaudi</td>
                        <td>4</td>
                        <td>Amdo, Mapia, Mejeni, Napiendi</td>
                    </tr>
                    <tr>
                        <td>Supiori Barat</td>
                        <td>Wayei</td>
                        <td>7</td>
                        <td>Amiyai, Kisyap, Mapia, Mejeni, Napiendi, Wayei</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock main %} 

templates/setori/potensidaerah/distrik_lengkap.html
{% extends 'setori/base_layout/base_layout.html' %} 
{% load static %}

{% block css %}
<style>
/* Dropdown Button Styles */
.dropbtn {
    background-color: #367588;
    color: white;
    padding: 12px 20px;
    font-size: 16px;
    border: none;
    border-radius: 5px;
    cursor: pointer;
    position: relative;
    transition: background-color 0.3s;
    display: flex;
    align-items: center;
}

.dropbtn i {
    margin-left: 5px; /* Spasi antara teks dan ikon */
}

/* Change background color on hover */
.dropbtn:hover {
    background-color: #367588;
}

/* Dropdown Container Styles */
.dropdown {
    position: relative;
    display: inline-block;
}

/* Dropdown Content Styles */
.dropdown-content {
    display: none;
    position: absolute;
    background-color: #ffffff;
    min-width: 160px;
    box-shadow: 0px 8px 16px rgba(0, 0, 0, 0.2);
    z-index: 1;
    border-radius: 5px;
    opacity: 0; /* Awalnya tidak terlihat */
    transition: opacity 0.3s ease;
    transform: translateY(10px); /* Efek sliding */
}

/* Dropdown links */
.dropdown-content a {
    color: #333;
    padding: 12px 16px;
    text-decoration: none;
    display: block;
    transition: background-color 0.3s;
}

/* Change background color on hover */
.dropdown-content a:hover {
    background-color: #f1f1f1;
}

/* Show Dropdown Content on Hover */
.dropdown:hover .dropdown-content {
    display: block;
    opacity: 1; /* Menampilkan dropdown */
    transform: translateY(0); /* Menghilangkan efek sliding */
}


/* Search bar */
/* Search Container Styles */
.search-container {
    display: flex;
    align-items: center;
}

/* Search Input Styles */
.search-input {
    padding: 10px 15px;
    border: 2px solid #367588;
    border-radius: 5px 0 0 5px;
    outline: none;
    font-size: 16px;
    width: 200px; /* Lebar input bisa disesuaikan */
    transition: border-color 0.3s;
}

/* Search Input Hover Effect */
.search-input:focus {
    border-color: #0056b3;
}

/* Search Button Styles */
.search-button {
    padding: 10px 15px;
    background-color: #367588;
    color: white;
    border: none;
    border-radius: 0 5px 5px 0;
    cursor: pointer;
    transition: background-color 0.3s;
    display: flex;
    align-items: center;
}

/* Change background color on hover */
.search-button:hover {
    background-color: #0056b3;
}

/* Font Awesome Icon Size */
.search-button i {
    font-size: 16px; /* Ukuran ikon */
}

</style>
{% endblock css %}

{% block main %}  
<!-- header -->
<div class="body">
    <div class="page-header" style="position: relative; margin-bottom: 0; overflow: hidden;">
        <img src="{% static 'img/header/atasan.jpg' %}" alt="Header Background" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; object-fit: cover; z-index: 0;">
        <div class="container p-relative z-index-1 py-2">
            <div class="row mh-200px mh-lg-300px align-items-center py-4">
                <div class="col">
                    <div class="appear-animation" data-appear-animation="fadeIn" data-appear-animation-delay="200">
                        <h1 class="text-9 text-lg-12 text-color-light font-weight-semibold line-height-1 mb-2">Potensi Daerah Distrik</h1>
                    </div>
                    <div class="appear-animation" data-appear-animation="fadeIn" data-appear-animation-delay="200">
                        <ul class="breadcrumb d-flex text-3-5 font-weight-semi-bold pb-2 mb-3">
                            <li><a href="{% url 'app_setori:index_home' %}"  class="text-light text-decoration-none">Beranda</a></li>
                            <li class="active text-color-light opacity-7">Potensi Daerah</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="bg-grey-100 px-3 px-xl-0 border-radius-2-bottom p-relative overflow-hidden">
    
    <!--Potensi-->
    <div class="container">
        <div class="row pt-5">
            <div class="col-lg-6 mb-4">
                <a href="" class="text-decoration-none">
                <div class="border-radius-2 overflow-hidden">
                    <span class="thumb-info thumb-info-no-overlay thumb-info-show-hidden-content-hover">
                        <span class="thumb-info-wrapper border-radius-0 rounded-top">
                            <img src="{% static 'img/potensi/1.jpg' %}" loading="lazy" class="img-fluid" alt="">
                        </span>
                        <span class="thumb-info-content">
                            <span class="thumb-info-content-inner bg-light p-4">
                                <h4 class="text-5 mb-1">Supiori Selatan</h4>
                                <p class="line-height-7 text-3 mb-0">Distrik: Supiori Selatan</p>
                                <p class="line-height-7 text-3 mb-0">Kepala Desa: Drs. Yan Imbab </p>
                                <p class="line-height-7 text-3 mb-0">Perkiraan jumlah keluarga: 92</p>
                            </span>
                        </span>
                    </span>
                </div>
                </a>
            </div>
            <div class="col-lg-6 mb-4">
                <div class="border-radius-2 overflow-hidden">
                    <span class="thumb-info thumb-info-no-overlay thumb-info-show-hidden-content-hover">
                        <span class="thumb-info-wrapper border-radius-0 rounded-top">
                            <img src="{% static 'img/potensi/2.jpg' %}" loading="lazy" class="img-fluid" alt="">
                        </span>
                        <span class="thumb-info-content">
                        <span class="thumb-info-content-inner bg-light p-4">
                                <h4 class="text-5 mb-1">Kepulauan Aruri</h4>
                                <p class="line-height-7 text-3 mb-0">Distrik: Kepulauan Aruri</p>
                                <p class="line-height-7 text-3 mb-0">Kepala Desa: Drs. Yan Imbab</p>
                                <p class="line-height-7 text-3 mb-0">Perkiraan jumlah keluarga: 51</p>
                            </span>
                        </span>
                    </span>
                </div>
            </div>
            <div class="col-lg-6 mb-4">
                <div class="border-radius-2 overflow-hidden">
                    <span class="thumb-info thumb-info-no-overlay thumb-info-show-hidden-content-hover">
                        <span class="thumb-info-wrapper border-radius-0 rounded-top">
                            <img src="{% static 'img/potensi/3.jpg' %}" loading="lazy" class="img-fluid" alt="">
                        </span>
                        <span class="thumb-info-content">
                        <span class="thumb-info-content-inner bg-light p-4">
                                <h4 class="text-5 mb-1">Supiori Utara</h4>
                                <p class="line-height-7 text-3 mb-0">Distrik: Supiori Utara</p>
                                <p class="line-height-7 text-3 mb-0">Kepala Desa: Drs. Yan Imbab</p>
                                <p class="line-height-7 text-3 mb-0">Perkiraan jumlah keluarga: 36</p>
                            </span>
                            <span class="thumb-info-content-inner-hidden p-absolute d-block w-100 py-3">
                                                                <ul class="social-icons social-icons-clean social-icons-medium">
                                                                    <li class="social-icons-instagram">
                                                                        <a href="http://www.instagram.com/" target="_blank" title="Instagram">
                                                                            <i class="fab fa-instagram"></i>
                                                                        </a>
                                                                    </li>
                                                                    <li class="social-icons-x">
                                                                        <a href="http://www.x.com/" target="_blank" title="X">
                                                                            <i class="fab fa-x-twitter"></i>
                                                                        </a>
                                                                    </li>
                                                                    <li class="social-icons-facebook">
                                                                        <a href="http://www.facebook.com/" target="_blank" title="Facebook">
                                                                            <i class="fab fa-facebook-f"></i>
                                                                        </a>
                                                                    </li>
                                                                </ul>
															</span>
                        </span>
                    </span>
                </div>
            </div>
            <div class="col-lg-6 mb-4">
                <div class="border-radius-2 overflow-hidden">
                    <span class="thumb-info thumb-info-no-overlay thumb-info-show-hidden-content-hover">
                        <span class="thumb-info-wrapper border-radius-0 rounded-top">
                            <img src="{% static 'img/potensi/4.jpg' %}" loading="lazy" class="img-fluid" alt="">
                        </span>
                        <span class="thumb-info-content">
                        <span class="thumb-info-content-inner bg-light p-4">
                                <h4 class="text-5 mb-1">Supiori Barat</h4>
                                <p class="line-height-7 text-3 mb-0">Distrik: Supiori Barat</p>
                                <p class="line-height-7 text-3 mb-0">Kepala Desa: Drs. Yan Imbab</p>
                                <p class="line-height-7 text-3 mb-0">Perkiraan jumlah keluarga: 786</p>
                            </span>
                        </span>
                    </span>
                </div>
            </div>
            <div class="pt-3 pb-5">
                <ul class="pagination pagination-rounded pagination-md justify-content-center">
					<li class="page-item"><a class="page-link bg-transparent text-dark" href="#" data-cursor-effect-hover="fit"><i class="fas fa-angle-left"></i></a></li>
					<li class="page-item active"><a class="page-link bg-secondary text-light border-color-secondary" href="#" data-cursor-effect-hover="fit">1</a></li>
					<li class="page-item"><a class="page-link bg-transparent text-dark" href="#" data-cursor-effect-hover="fit">2</a></li>
					<li class="page-item"><a class="page-link bg-transparent text-dark" href="#" data-cursor-effect-hover="fit"><i class="fas fa-angle-right"></i></a></li>
				</ul>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock main %} 

templates/setori/potensidaerah/index.html
{% extends 'setori/base_layout/base_layout.html' %} 
{% load static %}

{% block css %}
<style>
/* Dropdown Content Styles */
.dropdown-content {
    display: none;
    position: absolute;
    background-color: #ffffff;
    min-width: 160px;
    box-shadow: 0px 8px 16px rgba(0, 0, 0, 0.2);
    z-index: 1;
    border-radius: 5px;
    opacity: 0; /* Awalnya tidak terlihat */
    transition: opacity 0.3s ease;
    transform: translateY(10px); /* Efek sliding */
}

/* Dropdown links */
.dropdown-content a {
    color: #333;
    padding: 12px 16px;
    text-decoration: none;
    display: block;
    transition: background-color 0.3s;
}

/* Change background color on hover */
.dropdown-content a:hover {
    background-color: #f1f1f1;
}

/* Show Dropdown Content on Hover */
.dropdown:hover .dropdown-content {
    display: block;
    opacity: 1; /* Menampilkan dropdown */
    transform: translateY(0); /* Menghilangkan efek sliding */
}

.img_setting {
    width: 400px;
    height: 400px;
    object-fit: fill; /* Membuat gambar mengisi area 400x400, meskipun harus terdistorsi */
}

</style>
{% endblock css %}

{% block main %}  
<!-- header -->
<div class="body">
    <div class="page-header" style="position: relative; margin-bottom: 0; overflow: hidden;">
        <img src="{% static 'img/header/atasan.jpg' %}" alt="Header Background" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; object-fit: cover; z-index: 0;">
        <div class="container p-relative z-index-1 py-2">
            <div class="row mh-200px mh-lg-300px align-items-center py-4">
                <div class="col">
                    <div class="appear-animation" data-appear-animation="fadeIn" data-appear-animation-delay="200">
                        <h1 class="text-9 text-lg-12 text-color-light font-weight-semibold line-height-1 mb-2">Potensi Daerah</h1>
                    </div>
                    <div class="appear-animation" data-appear-animation="fadeIn" data-appear-animation-delay="200">
                        <ul class="breadcrumb d-flex text-3-5 font-weight-semi-bold pb-2 mb-3">
                            <li><a href="{% url 'app_setori:index_home' %}"  class="text-light text-decoration-none">Beranda</a></li>
                            <li class="active text-color-light opacity-7">Potensi Daerah</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="bg-grey-100 px-3 px-xl-0 border-radius-2-bottom p-relative overflow-hidden">

    <!--Potensi-->
    <div class="container">
        <div class="row pt-5">
            {% for potensi in page_obj %}
            <div class="col-lg-6 mb-4">
                <a href="{% url 'app_setori:detail' potensi.info_wilayah_id %}" class="text-decoration-none">
                <div class="border-radius-2 overflow-hidden appear-animation" data-appear-animation="fadeInUpShorter" data-appear-animation-delay="400">
                    <span class="thumb-info thumb-info-no-overlay thumb-info-show-hidden-content-hover">
                        <span class="thumb-info-wrapper border-radius-0 rounded-top">
                            <img src="{{ potensi.image_profile.url }}" loading="lazy" class="img-fluid img_setting" alt="">
                        </span>
                        <span class="thumb-info-content">
                            <span class="thumb-info-content-inner bg-light p-4">
                                <h4 class="text-5 mb-2 text-center">
                                    {{ potensi.wilayah.wilayah_nama }}
                                </h4>
                                <h4 class="text-5 mb-2">- Tahun Pembentukan: {{ potensi.tahun_pembentukan }} </h4>
                                <h4 class="text-5 mb-2">- Kode Pos: {{ potensi.kode_pos }}</h4>
                                <!-- <table border="1">
                                    <thead>
                                        <tr>
                                            <th>Wilayah Parent</th>
                                            <th>Total Pria OAP</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for item in Total %}
                                            <tr>
                                                <td>{{ item.wilayah__wilayah_parent__wilayah_nama }}</td>
                                                <td>{{ item.total_pria_oap }}</td>
                                            </tr>
                                        {% endfor %}
                                    </tbody>
                                </table> -->
                            </span>
                        </span>
                    </span>
                </div>
                </a>
            </div>
            {% endfor %}
            
            <!-- Kontrol Pagination -->
            <div class="pt-3 pb-5">
                <ul class="pagination pagination-rounded pagination-md justify-content-center">
                    <!-- Previous Page Link -->
                    {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link bg-transparent text-dark" href="?page={{ page_obj.previous_page_number }}" data-cursor-effect-hover="fit"><i class="fas fa-angle-left"></i></a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <span class="page-link bg-transparent text-dark"><i class="fas fa-angle-left"></i></span>
                    </li>
                    {% endif %}

                    <!-- Page Number Links -->
                    {% for num in page_obj.paginator.page_range %}
                    {% if page_obj.number == num %}
                    <li class="page-item active"><a class="page-link bg-secondary text-light border-color-secondary" href="?page={{ num }}" data-cursor-effect-hover="fit">{{ num }}</a></li>
                    {% elif num > page_obj.number|add:-3 and num < page_obj.number|add:3 %}
                    <li class="page-item"><a class="page-link bg-transparent text-dark" href="?page={{ num }}" data-cursor-effect-hover="fit">{{ num }}</a></li>
                    {% endif %}
                    {% endfor %}

                    <!-- Next Page Link -->
                    {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link bg-transparent text-dark" href="?page={{ page_obj.next_page_number }}" data-cursor-effect-hover="fit"><i class="fas fa-angle-right"></i></a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <span class="page-link bg-transparent text-dark"><i class="fas fa-angle-right"></i></span>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock main %} 